### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by rishiraj824** [gitshubho/BROSource#11]
Fix height of the home page slide show. So that the content doesn't go up and down. Also make the slider full height of the viewport, give it a height of min 100vh. (Use min-height:100vh;)

**Comment by rishiraj824** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/11540785/15983381/9340768a-2fc3-11e6-91fd-2eb42b229a63.png)
INcrease the font size as in the design and make the contents aligned. the profile photo and the content below it.

**Comment by rishiraj824** [comment]
Make the card length of featured and recent shorter since it looks empty.

**Comment by rishiraj824** [comment]
There is excessive padding in the footer.

**Comment by AnkurSarode** [comment]
Solved all mentioned issues, please check if i missed out anything.

**Comment by ashwini0529** [comment]
@rishiraj824 close the issue once it's done
