### ISSUE TITLE
User Data not aligned in Profile

### ISSUE THREAD

**Issue by ashwini0529** [gitshubho/BROSource#3]
At /profile, the user data is not aligned properly.
Please refer below screenshot:
![screenshot from 2016-04-15 17-36-34](https://cloud.githubusercontent.com/assets/8419333/14560948/a0019288-0330-11e6-805f-d08696351ecb.png)

**Comment by ashwini0529** [comment]
@AnkurSarode status?

**Comment by AnkurSarode** [comment]
This issue has been solved.

**Comment by ashwini0529** [comment]
Please refer the commit id.
