### ISSUE TITLE
Frontend for Donate

### ISSUE THREAD

**Issue by ashwini0529** [gitshubho/BROSource#6]
The backend is done at` /donate` which renders `donate.html` template . Add frontend to the `donate.html `template .

Close this issue when done.
Deadline : By tonight.

**Comment by rahulakrishna** [comment]
Added frontend to donate-view.html,
Uses the form from donate.html
Originally it had to slide in from the right side in profile_others.
But slide in utilizes the whole page and requires to be on top of everything which will covers the donate button beneath it. And makes it unable to click.
It will require both the button and slide in being in the same div, which will require the whole page architecture to change. 
Will start working on the Slidein soon as every other functionality is done.

**Comment by ashwini0529** [comment]
Hope you close the issue by tonight. @rahulakrishna

**Comment by ashwini0529** [comment]
Whenever you close any issue, mention the commit in which you've closed the issue.
Leave the commit with `fixed #issue-number`
