### ISSUE TITLE
Forgot password Frontend

### ISSUE THREAD

**Issue by ashwini0529** [gitshubho/BROSource#7]
The backend is done at `/forgot/verify` and `/forgot/authToken` which renders `forgot.html` and `forgot_verify.html` template . Add frontend to it. Do this in modal. Also, give a link to `Forgot Password` in `Login` modal.
Close this issue when done.
Deadline : By tonight.

**Comment by rahulakrishna** [comment]
The Submit button in Forgot Password modal goes to another page, 
So the button that opens Verify OTP modal is a different one right now,

If the submit button won't open a different page in production, We can place the <input type="submit"... into <a href="#modal"...

Else, we can go for a different page for OTP verification.
